#!/bin/sh /etc/rc.common
# DIY Multi-WAN Monitor Unit File
# Location:  /etc/init.d/mwan-diy
# Version 7 - Leave only crucial parts

USE_PROCD=1
START=98
STOP=01
NAME=mwan-diy

start_service() {
    procd_open_instance
    logger -t "${NAME}" "Service starting..."
    procd_set_param command /etc/multi_wan_monitor.sh
    procd_set_param respawn \
      ${respawn_threshold:-3600} \
      ${respawn_timeout:-5} \
      ${respawn_retry:-5}
    procd_set_param pidfile /var/run/${NAME}.pid

    # Enable log capture for stdout/stderr
    #procd_set_param stdout 1
    procd_set_param stderr 1

    procd_close_instance
}


